# Generated by Django 2.1.2 on 2019-01-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('email_reg', models.TextField(blank=True, null=True)),
                ('username_reg', models.TextField(blank=True, null=True)),
                ('password_reg', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
