# Generated by Django 2.1.2 on 2019-01-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('email_reg', models.EmailField(max_length=254)),
                ('username_reg', models.TextField()),
                ('password_reg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
