# Generated by Django 2.1.2 on 2019-01-12 14:36

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190112_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete='do_nothing', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reg',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
