# Generated by Django 2.1.2 on 2019-01-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190112_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='user',
        ),
        migrations.AlterField(
            model_name='reg',
            name='gender',
            field=models.TextField(max_length=10),
        ),
    ]
